from collections import Counter
from datetime import UTC, datetime
from uuid import uuid4

from app.graphql.inputs import CodeInput
from app.graphql.types import CodeReview, DashboardStats, Suggestion


class ReviewService:
    def __init__(self) -> None:
        self._reviews: list[CodeReview] = []

    def analyze_code(self, input: CodeInput) -> CodeReview:
        language = input.language.strip()
        code = input.code.strip()
        title = input.title.strip() if input.title else None

        if not language:
            raise ValueError("Programming language is required.")

        if not code:
            raise ValueError("Code is required.")

        review = CodeReview(
            id=uuid4().hex,
            title=title,
            language=language,
            submitted_code=input.code,
            overall_score=100,
            summary=(
                "Mock review generated by the GraphQL skeleton. "
                "Rule-based and LLM analysis will be added in a later approved task."
            ),
            bugs=[],
            security_issues=[],
            performance_issues=[],
            suggestions=[
                Suggestion(
                    title="Analyzer engine pending",
                    explanation=(
                        "The API contract is ready; real bug, security, performance, "
                        "and quality checks are not wired yet."
                    ),
                    improved_code=None,
                )
            ],
            created_at=datetime.now(UTC).isoformat(),
        )
        self._reviews.insert(0, review)
        return review

    def list_reviews(self) -> list[CodeReview]:
        return list(self._reviews)

    def get_review(self, review_id: str) -> CodeReview | None:
        return next((review for review in self._reviews if str(review.id) == review_id), None)

    def get_dashboard_stats(self) -> DashboardStats:
        total_reviews = len(self._reviews)
        total_score = sum(review.overall_score for review in self._reviews)
        language_counts = Counter(review.language for review in self._reviews)

        return DashboardStats(
            total_reviews=total_reviews,
            average_score=(total_score / total_reviews) if total_reviews else 0.0,
            total_bugs=sum(len(review.bugs) for review in self._reviews),
            total_security_issues=sum(len(review.security_issues) for review in self._reviews),
            most_used_language=language_counts.most_common(1)[0][0] if language_counts else None,
        )


review_service = ReviewService()
